# Generated by Django 5.2.1 on 2025-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_password',
            field=models.CharField(blank=True, null=True, verbose_name='Текущий пароль'),
        ),
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, null=True, verbose_name='Новый пароль'),
        ),
    ]
