# Generated by Django 5.2.1 on 2025-06-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_day_user_current_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='new_password',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
