# Generated by Django 5.2.1 on 2025-07-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
    ]
